services:
  postgres:
    image: postgres:16
    container_name: booking-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: booking
      POSTGRES_PASSWORD: booking
      POSTGRES_DB: platform_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.7.3
    container_name: booking-keycloak
    restart: unless-stopped

    command: start-dev

    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

    ports:
      - "127.0.0.1:8081:8080"

    volumes:
      - keycloak_data:/opt/keycloak/data

volumes:
  postgres_data:
  keycloak_data:
