import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { MapPin, Plus, Users } from "lucide-react";
import SearchSelect from "../../components/SearchSelect";
import { getStaff, saveStaff, staffValues, type StaffMember } from "../staff/staffApi";
import { invalidateBookingData } from "../assignments/invalidateBookingData";
export default function LocationStaffPanel({ locationId, locationName }: { locationId: string; locationName: string }) {
    const client = useQueryClient(); const query = useQuery({ queryKey: ["staff"], queryFn: getStaff }); const [selectedId, setSelectedId] = useState(""); const [pending, setPending] = useState(false); const [error, setError] = useState("");
    async function update(member: StaffMember, locationIds: string[], freeAgent: boolean) { setPending(true); setError(""); try { await saveStaff({ ...staffValues(member), freeAgent, locationIds }, member.id); await invalidateBookingData(client); setSelectedId(""); } catch (e) { setError(e instanceof Error ? e.message : "Could not update assigned staff."); } finally { setPending(false); } }
    if (query.isPending) return <p>Loading assigned staff…</p>; if (query.error) return <p className="form-error" role="alert">{query.error.message}</p>;
    const assigned = query.data.filter(member => !member.freeAgent && member.locationIds.includes(locationId)); const freeAgents = query.data.filter(member => member.freeAgent && member.active); const candidates = query.data.filter(member => member.active && !assigned.some(assigned => assigned.id === member.id)); const selected = candidates.find(member => member.id === selectedId);
    return <section className="card management-panel tinted-panel sage-panel"><div className="section-heading"><h2><Users size={20} />Staff at {locationName}</h2><Link className="text-action" to="/staff">Manage staff</Link></div><div className="assignment-add-row"><SearchSelect value={selectedId} options={candidates.map(member => ({ value: member.id, label: member.name, description: member.freeAgent ? "Free agent · will be assigned here" : "Add this location to their assigned locations" }))} onChange={setSelectedId} ariaLabel="Assign staff to location" placeholder="Type a staff member's name…" disabled={pending} /><button className="button button-primary" disabled={pending || !selected} onClick={() => selected && update(selected, [...new Set([...selected.locationIds, locationId])], false)}><Plus size={15} />Assign here</button></div><p className="field-note">Assigning a free agent here limits them to selected locations. Services still control which staff and locations are eligible for each booking.</p>{error && <p className="form-error" role="alert">{error}</p>}<div className="assigned-team">{assigned.length === 0 ? <p className="field-note">No staff are limited to this location.</p> : assigned.map(member => <div className="assigned-person" key={member.id}><span className="staff-avatar">{member.name.slice(0, 1)}</span><div><strong>{member.name}</strong><small>{member.email || (member.active ? "Active" : "Inactive")}</small></div><button className="button button-secondary" disabled={pending} data-tooltip={member.locationIds.length === 1 ? "Allow this staff member to work at any service location." : "Remove only this location from their assigned locations."} onClick={() => update(member, member.locationIds.filter(id => id !== locationId), member.locationIds.length === 1)}>{member.locationIds.length === 1 ? "Make free agent" : "Unassign"}</button></div>)}</div><div className="free-agent-group"><p className="detail-line"><MapPin size={16} />Free agents can also work here</p><div className="selected-tags">{freeAgents.length === 0 ? <span className="field-note">No active free agents.</span> : freeAgents.map(member => <span className="selected-tag" key={member.id} data-tooltip={`${member.name}
Available at any eligible service location, subject to their schedule.`}>{member.name}</span>)}</div></div></section>;
}
